mail.Write.gzdyjtbqQybHL : 给指定邮件贴标签
mail.Write.youjian : 邮件:
mail.Write.zhanyong :  占用:
mail.Write.chuangjian : 创建
mail.Write.youjianfenjian : 邮件分拣
mail.Write.gzafjTPhAWclgfb : 规则，按发件人自动投到指定邮件夹，邮件处理更方便。
mail.Write.daishouyoujianjia : 代收邮件夹
mail.Write.wodebiaoqian : 我的标签
mail.Write.qxzysqdlxrtmcjq : 请选择要收取的联系人
mail.Write.znsryvFtjklxrdz : 只能输入一个联系人地址
mail.Write.qsrzqyHqmSlxrdz : 请输入正确的联系人地址
mail.Write.tmbqyjczvJFKG : 同名标签已经存在
mail.Write.xgbqcgAeBeo : 修改标签成功
mail.Write.cjbqcgqNClA : 创建标签成功
mail.Write.xgbqsbRzjln : 修改标签失败
mail.Write.bqsccgBxCLd : 标签删除成功
mail.Write.daibanrenwu : 待办任务
mail.Write.bqxgcgghlRf : 标签修改成功
mail.Write.cjbqsbZefUP : 创建标签失败
