mail.Write.jiemichenggong : 解密成功
mail.Write.mmcwqzxsrjhkgL : 密码错误,请重新输入
mail.Write.mmcwcbHuecfzhzs : 密码错误次数达到限制，请10分钟后重试
mail.Write.qdsxxpivqSzhzck : 请到收信箱解密此封邮件之后再查看
mail.Write.zhangdanmingxi : 账单明细
mail.Write.huiyiyaoqing : 会议邀请
mail.Write.daibanyoujian : 待办邮件
mail.Write.minganyoujian : 敏感邮件
mail.Write.xingbiaoyoujian : 星标邮件
mail.Write.nhywwsAUkxzsfgb : 您还有未完成编辑操作，是否关闭？
mail.Write.wjdrsbMdnmg : 文件导入失败
mail.Write.duanxin : 短信
mail.Write.ndllqnDDgNfcszt : 您的浏览器目前处于缩放状态，会导致邮箱显示不正常，您可以键盘按\"ctrl+数字键0\"组合键恢复初始状态。
mail.Write.wldkqGMttpcwllj : 网络断开，请检查网络连接.
mail.Write.yidu : 已读
mail.Write.buzaitishi : \"不再提示\
mail.Write.buzaitishi : 不再提示
mail.Write.ymmcwqzxsrBcmTX : 原密码错误, 请重新输入
mail.Write.xmmgsylwsLqzxsr : 新密码格式错误, 请重新输入
mail.Write.xgmmcgHzcJo : 修改密码成功
mail.Write.xgmmsbIUorO : 修改密码失败
mail.Write.xgmmsbhQiza : 修改密码失败
mail.Write.ndzhdORdwLaqqxg : 你的帐号的私钥密码为初始密码,为保障安全,请修改
mail.Write.wlbzarSzwcgsymm : 为了保障安全，请修改私钥密码
mail.Write.yuanmima : 原密码：
mail.Write.xinmima : 新密码：
mail.Write.querenmima : 确认密码：
mail.Write.symmxgRVrMc : 私钥密码修改
mail.Write.jmmbnwkRmfAM : 旧密码不能为空
mail.Write.mmcdxwrOfxt : 密码长度需6-64位
mail.Write.xmmbnwknULBW : 新密码不能为空
mail.Write.mmcdxwGcQyY : 密码长度需6-64位
mail.Write.qrmmbnwkfkzCT : 确认密码不能为空
mail.Write.mmcdxwXJnBP : 密码长度需6-64位
mail.Write.lcmmbMbHKEqzxsr : 两次密码不一致，请重新输入
mail.Write.jiemichenggong : 解密成功
mail.Write.jiemishibai : 解密失败
mail.Write.yhzdyzUjPDU : 以后自动验证
mail.Write.symmxgbYXgm : 私钥密码修改
mail.Write.cyjwsMjSYfxjmyj : 此邮件为数字加密邮件，需要输入你的私钥密码进行解密邮件。
mail.Write.mima : 密 码：
mail.Write.symmyzqJttT : 私钥密码验证
mail.Write.mmbnwkWGrYN : 密码不能为空
mail.Write.mmcdxweCjTV : 密码长度需6-64位
