mail.Write.yueripVpufWyr : yyyy-m月d日
mail.Write.beijingIhqTQvxm : 北京
mail.Write.tianjinNZQkSnQN : 天津
mail.Write.shanghaiHsYYGLKw : 上海
mail.Write.guangdongSPzJQQee : 广东
mail.Write.guangxiWBORfTyT : 广西
mail.Write.hebeiJXhKyozi : 河北
mail.Write.henanOhxnTXWi : 河南
mail.Write.hubeigOEbGypi : 湖北
mail.Write.hunanoYwisJbA : 湖南
mail.Write.fujianWIZscpgR : 福建
mail.Write.shandongFbqrhVrX : 山东
mail.Write.anhuiLScorcKX : 安徽
mail.Write.zhejiangWDyAnTdp : 浙江
mail.Write.sichuanijvjElVE : 四川
mail.Write.zhongqingIoUmIEYz : 重庆
mail.Write.guizhoutEpzMybI : 贵州
mail.Write.jiangsusKihxJWJ : 江苏
mail.Write.shanxitUMxUHUP : 山西
mail.Write.yunnanKeHXxYwu : 云南
mail.Write.liaoningPmkDMjZI : 辽宁
mail.Write.jilinnOQvFPmk : 吉林
mail.Write.namengguXXuMGgfW : 内蒙古
mail.Write.heilongjiangjuIdhcfJ : 黑龙江
mail.Write.xicangbjSQUxLw : 西藏
mail.Write.shanxiLiQVBkxE : 陕西
mail.Write.gansucGKlKFdz : 甘肃
mail.Write.qinghaieKByMGdX : 青海
mail.Write.xinjiangXUSlPHDF : 新疆
mail.Write.jiangxirfceNRgU : 江西
mail.Write.hainanYUkzrKAe : 海南
mail.Write.taiwanhEdrQKLl : 台湾
mail.Write.xianggangOxofdNxA : 香港
mail.Write.ningxiavbKxSyni : 宁夏
mail.Write.aomenJwsjOEQT : 澳门
mail.Write.guanbiSKDYjoqs : 关闭
mail.Write.shengfenitkubJdN : 省份==
mail.Write.dishidBqUuUGG : 地市==
mail.Write.chakanFPpBeDcr : 查看
mail.Write.sheweimorenchengshiaFuoiBUf : 设为默认城市
mail.Write.shujujiazaizhongqingshaohouqreerUYh : 数据加载中，请稍候....
mail.Write.chuanyizhishucchhnmgS : 穿衣指数
mail.Write.ganmaozhishuSiVraPzF : 感冒指数
mail.Write.chenlianzhishuJfdEQENE : 晨练指数
mail.Write.jiaotongzhishuBYLLykxD : 交通指数
mail.Write.zhongshuzhishuocFKQCzg : 中暑指数
mail.Write.gongyuanzhishupQMUHpeZ : 公园指数
mail.Write.fangshaizhishuOnbzmxEc : 防晒指数
mail.Write.lvxingzhishuAQTUwnXE : 旅行指数
mail.Write.tianjinvxdruVAT : 天津
mail.Write.shanghaiVklIBSdr : 上海
mail.Write.beijingWSgHLIxl : 北京
mail.Write.guangzhouYygrEomC : 广州
mail.Write.chaozhoucbUrtiMZ : 潮州
mail.Write.zhaoqingHJYOaDDS : 肇庆
mail.Write.heyuanFnIsqphb : 河源
mail.Write.shaoguanOkHSOIjU : 韶关
mail.Write.jieyangBCCGGJRk : 揭阳
mail.Write.shanweivQlkPPKi : 汕尾
mail.Write.meizhouDqkUWXPx : 梅州
mail.Write.huizhouQApGNJuI : 惠州
mail.Write.dongguanwDNVYpDE : 东莞
mail.Write.zhongshanWjtCrwRu : 中山
mail.Write.jiangmengiehfXLo : 江门
mail.Write.maomingwmkJKNpI : 茂名
mail.Write.yunfuSOQzHtwF : 云浮
mail.Write.yangjiangxmpzJDDY : 阳江
mail.Write.shantouybqpPVTI : 汕头
mail.Write.shenchouggkhgTwE : 深圳
mail.Write.zhuhaicctGpByP : 珠海
mail.Write.zhanjiangWFTrcYPY : 湛江
mail.Write.fushanVSCdmfys : 佛山
mail.Write.nanningILnkmBKB : 南宁
mail.Write.baiseaqWPFlNL : 百色
mail.Write.liuzhouATuiDgRZ : 柳州
mail.Write.wuzhoumgbffIUj : 梧州
mail.Write.yulinfLKmeblU : 玉林
mail.Write.guipinghQLlAocS : 桂平
mail.Write.hezhouAYLXBstH : 贺州
mail.Write.qinzhouWwEuMcBg : 钦州
mail.Write.guigangGhFhqmWx : 贵港
mail.Write.yangshuorhZLSBvp : 阳朔
mail.Write.guilinRyehkgbw : 桂林
mail.Write.beihaisymehjAP : 北海
mail.Write.hechiKAihfEBt : 河池
mail.Write.shijiazhuangsZiUsQKk : 石家庄
mail.Write.tangshanjZeWmCGB : 唐山
mail.Write.zhangjiakoupOtutLEm : 张家口
mail.Write.langfangkfpFVElH : 廊坊
mail.Write.handanMeKVvmwW : 邯郸
mail.Write.xingtaicXmTryUu : 邢台
mail.Write.cangzhouHGotYMSD : 沧州
mail.Write.hengshuibRbQnMFj : 衡水
mail.Write.chengdeDLcvrnsT : 承德
mail.Write.qinhuangdaojptKyRFM : 秦皇岛
mail.Write.baodingpsrCEZPI : 保定
mail.Write.zhengzhouTZCkMqCP : 郑州
mail.Write.kaifengihRnYNWf : 开封
mail.Write.anyangWdMSHMdb : 安阳
mail.Write.jiaozuoCYfwFJSq : 焦作
mail.Write.hebiNDtjfQRT : 鹤壁
mail.Write.pingdingshanciUwNXuG : 平顶山
mail.Write.shangqiurONNuXAn : 商丘
mail.Write.puyangwBoAjyeB : 濮阳
mail.Write.nanyangYJRWrzCD : 南阳
mail.Write.xuchangJiCTbiwL : 许昌
mail.Write.xinyangesYrgCuF : 信阳
mail.Write.qingyuanPfqVxslh : 清远
mail.Write.sanmenxiaSsepKKYF : 三门峡
mail.Write.zhumadianwNprCcZJ : 驻马店
mail.Write.zhoukouqyEBUHwX : 周口
mail.Write.xinxiangPKkcqmHT : 新乡
mail.Write.luoyangnbiYHEAN : 洛阳
mail.Write.kaifenghYYfWsUW : 开封
mail.Write.wuhanxvYXXDvf : 武汉
mail.Write.huanggangsdwgfoyt : 黄冈
mail.Write.enshiMvJDhUqj : 恩施
mail.Write.jingzhouMiPIdQVv : 荆州
mail.Write.shennongjiaPoGkHiMY : 神农架
mail.Write.shiyanPOttwwky : 十堰
mail.Write.xianningMTLErCPy : 咸宁
mail.Write.xiangfanvtCAeeei : 襄樊
mail.Write.xiaoganPsiDnQKQ : 孝感
mail.Write.suizhouGbocSLWa : 随州
mail.Write.huangshiTOQjdeYt : 黄石
mail.Write.jingmenHhZYELPQ : 荆门
mail.Write.ezhouvLjrNACP : 鄂州
mail.Write.yichangWQzSVLOJ : 宜昌
mail.Write.changshaOLitpdGg : 长沙
mail.Write.shaoyangfumMmJox : 邵阳
mail.Write.changdexPLcUpZc : 常德
mail.Write.chenzhouoLEXSkVI : 郴州
mail.Write.zhuzhouCbnBTaXZ : 株洲
mail.Write.jishouQvHxlvwp : 吉首
mail.Write.loudinJSXbVMN : 娄底
mail.Write.xiangtanLIUctHjw : 湘潭
mail.Write.yongzhoubDoYAwOR : 永州
mail.Write.yueyangRQVKxNjC : 岳阳
mail.Write.hengyangllqaDpAc : 衡阳
mail.Write.huaihuamCyPUwIb : 怀化
mail.Write.shaoshanTSXPWYHt : 韶山
mail.Write.zhangjiajieIjdnvUqH : 张家界
mail.Write.hengshanPYXIJubN : 衡山
mail.Write.fuzhoujgMWGypp : 福州
mail.Write.longyanrEGqkTqC : 龙岩
mail.Write.nanpingCEgoYWEW : 南平
mail.Write.ningdecTFsqpoQ : 宁德
mail.Write.putianvUPcoAlR : 莆田
mail.Write.quanzhouMebdCKYY : 泉州
mail.Write.sanmingMVrMjWXr : 三明
mail.Write.zhangzhouvVCsEufb : 漳州
mail.Write.xiamenpUtLCoTJ : 厦门
mail.Write.wuyishanshiHNvpccMS : 武夷山市
mail.Write.jinanqBrVXMzO : 济南
mail.Write.zaozhuangKrKiuFUq : 枣庄
mail.Write.liaochengkRlUpkxA : 聊城
mail.Write.qufuLRrYeEOF : 曲阜
mail.Write.jiningTpFvIyEZ : 济宁
mail.Write.linyiBPZVULtT : 临沂
mail.Write.hezeAweJAMVx : 菏泽
mail.Write.taianyHZJWOZw : 泰安
mail.Write.rizhaodXFFlBUe : 日照
mail.Write.dongyingniRXqzmj : 东营
mail.Write.qingdaomdeEUkXw : 青岛
mail.Write.weihairkswAVSI : 威海
mail.Write.taishanNHxWvbkD : 泰山
mail.Write.yantaiPBGCSQPJ : 烟台
mail.Write.weifangeqcjOsmB : 潍坊
mail.Write.zibopMSavfUc : 淄博
mail.Write.hefeiPYKYmwCV : 合肥
mail.Write.chaohujIRRndfh : 巢湖
mail.Write.bangbujiHUoPrX : 蚌埠
mail.Write.anqingGUrIiPDh : 安庆
mail.Write.liuanXFooXJNh : 六安
mail.Write.chuzhouSqsWjiQA : 滁州
mail.Write.maanshanfPlBymms : 马鞍山
mail.Write.fuyangNcmHtdOb : 阜阳
mail.Write.xuanchengKAQDyMCC : 宣城
mail.Write.tonglingsKSuVYhd : 铜陵
mail.Write.huaibeisMuUSXqf : 淮北
mail.Write.wuhukiwdYaeu : 芜湖
mail.Write.bozhouTnwsmvAK : 亳州
mail.Write.suzhouFCfnBvYn : 宿州
mail.Write.huainanuisNEdSz : 淮南
mail.Write.huangshanzhanFgVNykrv : 黄山站
mail.Write.jiuhuashanghebGIMk : 九华山
mail.Write.hangzhoukWhAfFRf : 杭州
mail.Write.huzhouSKUICXro : 湖州
mail.Write.jinhuaBvahuimd : 金华
mail.Write.ningbocXnDiMmg : 宁波
mail.Write.lishuiUXXBBpGd : 丽水
mail.Write.quzhouPUxjwEZv : 衢州
mail.Write.jiaxingtRVvufDC : 嘉兴
mail.Write.taizhousybETzAE : 台州
mail.Write.zhoushanZuOrOYXg : 舟山
mail.Write.yinxianrwNKIvAw : 鄞县
mail.Write.leqingdoXlkLVh : 乐清
mail.Write.wenzhoutqTPxRbw : 温州
mail.Write.zhoushanwiJrSlTf : 舟山
mail.Write.chengdumkIMsEbN : 成都
mail.Write.luzhouvtJVzSFR : 泸州
mail.Write.najiangpMbixLAI : 内江
mail.Write.liangshanadpsfrUn : 凉山
mail.Write.abaFeXskWtQ : 阿坝
mail.Write.bazhongTysriZoe : 巴中
mail.Write.guangyuanZDMXFuJg : 广元
mail.Write.leshanLgSkhWms : 乐山
mail.Write.mianyangCBUtykMH : 绵阳
mail.Write.panzhihuajCVkzulg : 攀枝花
mail.Write.yaanSabylsuc : 雅安
mail.Write.yibinAJyeYmmX : 宜宾
mail.Write.zigongzWAZOwqN : 自贡
mail.Write.ganzizhouWMNmbHhQ : 甘孜州
mail.Write.dazhouIlzgLksF : 达州
mail.Write.deyangYYKzRilA : 德阳
mail.Write.emeishanGmFFDHUJ : 峨眉山
mail.Write.zhongqingVQumMWXe : 重庆
mail.Write.guiyangXPrrfsyd : 贵阳
mail.Write.anshunJOwnnqtN : 安顺
mail.Write.chishuiaztgxQdP : 赤水
mail.Write.zunyihzYqbHmq : 遵义
mail.Write.tongrenDzHyOrnn : 铜仁
mail.Write.liupanshuiZTazcIdR : 六盘水
mail.Write.bijiesJfwOfiR : 毕节
mail.Write.kailicnOIykQf : 凯里
mail.Write.duyunUSjJHcml : 都匀
mail.Write.tongshiLicMcTaT : 通什
mail.Write.kunmingpupKzfTY : 昆明
mail.Write.baoshanoGvOsQqi : 保山
mail.Write.chuxiongsynKOenA : 楚雄
mail.Write.dehongbujqkyXB : 德宏
mail.Write.hongheoKRngZKh : 红河
mail.Write.lincangucnqUUyL : 临沧
mail.Write.nujianghcjDFGfF : 怒江
mail.Write.qujingkRnOIpVU : 曲靖
mail.Write.simaoHonpjBsa : 思茅
mail.Write.wenshanxhXhmPGG : 文山
mail.Write.yuxicTIEtDXg : 玉溪
mail.Write.zhaotongEDqXgDjN : 昭通
mail.Write.dalitTLdTtKG : 大理
mail.Write.lijiangPoKJRoGL : 丽江
mail.Write.deqinIxvsvsnF : 德钦
mail.Write.kunshanGOUoynfY : 昆山
mail.Write.nanjingOMTDDvyQ : 南京
mail.Write.nantongFBppRqkC : 南通
mail.Write.taicangpGYLXJFT : 太仓
mail.Write.suzhouLdsojWSG : 苏州
mail.Write.xuzhoukFbrkSMA : 徐州
mail.Write.yixingQvIedKOm : 宜兴
mail.Write.zhenjiangrvwrBnVv : 镇江
mail.Write.huaianCxzXYBWu : 淮安
mail.Write.changshupcVzbVnu : 常熟
mail.Write.yanchengjkCbgAeM : 盐城
mail.Write.taizhouueUxLddS : 泰州
mail.Write.suzhouiTUHnVGd : 苏州
mail.Write.wuxisyNBMJry : 无锡
mail.Write.lianyungangJdcnAzPN : 连云港
mail.Write.yangzhouiwlLKJSo : 扬州
mail.Write.changzhouzhFkBfMs : 常州
mail.Write.taiyuanYDPyqHMv : 太原
mail.Write.yangquanlyoEMxHF : 阳泉
mail.Write.jinchengCHpblNKg : 晋城
mail.Write.jinzhongrLxOVtAn : 晋中
mail.Write.linfenpgjXuUJz : 临汾
mail.Write.yunchengzlPIHsYY : 运城
mail.Write.changzhiKzmtzqbX : 长治
mail.Write.shuozhouDGEFKdFA : 朔州
mail.Write.xinzhouMjwVgIRU : 忻州
mail.Write.datongeFABEhuR : 大同
mail.Write.wutaishannFCrdPRK : 五台山
mail.Write.shenyangksQMBCuv : 沈阳
mail.Write.huludaolpScObqj : 葫芦岛
mail.Write.lvshunnhPMscRz : 旅顺
mail.Write.benxilMhTISGj : 本溪
mail.Write.chaoyangPUSKUPdD : 朝阳
mail.Write.fushunnGLcsrtn : 抚顺
mail.Write.liaoyangcGcPxnwg : 辽阳
mail.Write.tielingbroyMPZF : 铁岭
mail.Write.yingkouPeOipzWJ : 营口
mail.Write.fuxinepMWjoBx : 阜新
mail.Write.dalianZEsUqYEU : 大连
mail.Write.anshanrooizNqW : 鞍山
mail.Write.changchunMbzgCFhB : 长春
mail.Write.yanjiEPHtecVv : 延吉
mail.Write.jinzhoukCWLvCMQ : 锦州
mail.Write.jilinlBEvwhLX : 吉林
mail.Write.baishanmVpjFksP : 白山
mail.Write.baichengCaXNYDZd : 白城
mail.Write.sipingguXFeBhH : 四平
mail.Write.dandongYWFyJcBz : 丹东
mail.Write.songyuanXdqPBgvW : 松原
mail.Write.liaoyuanUtSlehJr : 辽源
mail.Write.changbaiJYFbaQhd : 长白
mail.Write.daanPjJjWxIQ : 大安
mail.Write.tonghuaGTPuoTRN : 通化
mail.Write.huhehaoteUomKBeXt : 呼和浩特
mail.Write.baotouxpEosHgt : 包头
mail.Write.chifengjePctcKb : 赤峰
mail.Write.hailaerOURiiQjM : 海拉尔
mail.Write.xilinhaoteAzeRtgqt : 锡林浩特
mail.Write.wuhaiTfMpiShc : 乌海
mail.Write.eerduositTdLxDyt : 鄂尔多斯
mail.Write.yakeshitkLArdKn : 牙克石
mail.Write.manzhoulijmwlMDLS : 满洲里
mail.Write.haerbinIOdybOLp : 哈尔滨
mail.Write.mudanjiangEDwsjyAb : 牡丹江
mail.Write.qiqihaeryRTIRXfx : 齐齐哈尔
mail.Write.daqingpYmUlpcR : 大庆
mail.Write.yichunlwXKTTOi : 伊春
mail.Write.shuangyashanyyGhTHgx : 双鸭山
mail.Write.hegangsuKSTNEZ : 鹤岗
mail.Write.jixixwoYcKan : 鸡西
mail.Write.jiamusiLhsVBLjH : 佳木斯
mail.Write.qitaihekXugTsVY : 七台河
mail.Write.suihuaNWzwzHHs : 绥化
mail.Write.heiheWhMCWHEL : 黑河
mail.Write.mudanjianglTiCBFzG : 牡丹江
mail.Write.daxinganlingObvoTvQq : 大兴安岭
mail.Write.heiheJBEvTLsG : 黑河
mail.Write.lasaqeQxlMkk : 拉萨
mail.Write.changduODYDRDNq : 昌都
mail.Write.alicXAKINSe : 阿里
mail.Write.naquLGgDywkz : 那曲
mail.Write.rikazeTMEThVjI : 日喀则
mail.Write.shannanpJWwZxbm : 山南
mail.Write.linzhivwmEocDq : 林芝
mail.Write.xianzjqZhumG : 西安
mail.Write.hanchengNgfyiwtE : 韩城
mail.Write.hanzhongcqlJzKdR : 汉中
mail.Write.baojiRoGOGxGe : 宝鸡
mail.Write.xianyangIkxuOkzK : 咸阳
mail.Write.yulinzrOfmFmP : 榆林
mail.Write.weinanyzIujpYJ : 渭南
mail.Write.shangzhoutmSUkLcs : 商州
mail.Write.huashankqLuuHLW : 华山
mail.Write.tongchuanVXBCtfAt : 铜川
mail.Write.lanzhourJbdSiKU : 兰州
mail.Write.baiyiniidoYSoy : 白银
mail.Write.jiuquanMdVdonTD : 酒泉
mail.Write.tianshuijKRwKSmz : 天水
mail.Write.wuweiINSufXzs : 武威
mail.Write.zhangyecAPwJMts : 张掖
mail.Write.gannaneseLsciW : 甘南
mail.Write.linxiaHVzpUevp : 临夏
mail.Write.pingliangFbFkSDWy : 平凉
mail.Write.dingximFvuCmah : 定西
mail.Write.qingyangSdhWVzyx : 庆阳
mail.Write.yananRzCFqdNe : 延安
mail.Write.jinchangdIrDiEqf : 金昌
mail.Write.dunhuangGLiFoepI : 敦煌
mail.Write.xiningdSCydNwx : 西宁
mail.Write.haibeivbqpXYdL : 海北
mail.Write.haixiFKRshitM : 海西
mail.Write.hainanoiMlrLTs : 海南
mail.Write.huangnanSXQYrAsn : 黄南
mail.Write.haidongNnDKtMER : 海东
mail.Write.guoluoCTMtirtF : 果洛
mail.Write.yushusuRuDgUI : 玉树
mail.Write.yinchuanFdJIzxXR : 银川
mail.Write.guyuannbVONzxG : 固原
mail.Write.zhongweicGrJEtbM : 中卫
mail.Write.shizuishanZwrLTOpq : 石嘴山
mail.Write.wuzhongXAJhaOOt : 吴忠
mail.Write.wulumuqiaFTyXyWV : 乌鲁木齐
mail.Write.aletaiaSelgwOi : 阿勒泰
mail.Write.akesuwRUCQgPt : 阿克苏
mail.Write.changjiDkSsNaXH : 昌吉
mail.Write.hamiwSDJenAu : 哈密
mail.Write.hetianPbiFsuez : 和田
mail.Write.kashiVwLFZxyf : 喀什
mail.Write.kelamayiNAiLNmuU : 克拉玛依
mail.Write.shihezidToJERwg : 石河子
mail.Write.tachengwtyISiHA : 塔城
mail.Write.kuerlenZFBcfOC : 库尔勒
mail.Write.yiningAmAdgUOj : 伊宁
mail.Write.tulufandUfsdDVm : 吐鲁番
mail.Write.nanchangoNbcsSRg : 南昌
mail.Write.jinggangshanMEfdygQK : 井冈山
mail.Write.pingxiangDqicUCqT : 萍乡
mail.Write.jiujiangKnQozcRz : 九江
mail.Write.shangraoRQbCgFOm : 上饶
mail.Write.fuzhouNcvqPLXh : 抚州
mail.Write.jiandOJsVAVS : 吉安
mail.Write.yingtanHkhDyJqX : 鹰潭
mail.Write.yichunhSTQGgzR : 宜春
mail.Write.lushanlsidIYBd : 庐山
mail.Write.ganzhouFzyscrYt : 赣州
mail.Write.duchangOdzYUvnd : 都昌
mail.Write.xinyuYNNPjAdr : 新余
mail.Write.jingdezhenbcLocEiY : 景德镇
mail.Write.haikouINlvMpep : 海口
mail.Write.danzhouMXwaMpKq : 儋州
mail.Write.qiongshanRcEHrPQF : 琼山
mail.Write.tongshivvuAVJGi : 通什
mail.Write.wenchangBiDRxeGf : 文昌
mail.Write.sanyaxyTDrvjR : 三亚
mail.Write.xishaQfOsdJxG : 西沙
mail.Write.nanshadaoHLANLFgx : 南沙岛
mail.Write.taibeiYYKvKXGL : 台北
mail.Write.gaoxiongigTXwLot : 高雄
mail.Write.xianggangYMrhNhwh : 香港
mail.Write.aomenzVKpUkDh : 澳门
